name: jruby-bundler

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  jruby_bundler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby-9.2.11.0
      - name: Install dependencies
        run: |
          bin/rake spec:deps
        working-directory: ./bundler
      - name: Run specs
        run: |
          bin/rspec spec
        working-directory: ./bundler
      - name: Install local bundler
        run: |
          bin/rake install:local
        working-directory: ./bundler
      - name: Run a warbler project
        run: |
          cd spec/realworld/fixtures/warbler
          bundle install
          bundle exec warble
          java -jar warbler.jar
        working-directory: ./bundler
